services:
  broker:
    image: docker.io/library/redis:8
    restart: always
    volumes:
      - /volume1/paperless/data/redisdata:/data
    networks:
      - db-net

  paperless:
    image: ghcr.io/paperless-ngx/paperless-ngx:2.20
    restart: always
    depends_on:
      - broker
    ports:
      - "8000:8000"
    volumes:
      - /volume1/my_apps/20-paperless-ngx/data/data:/usr/src/paperless/data
      - /volume1/my_apps/20-paperless-ngx/data/media:/usr/src/paperless/media
      - /volume1/my_apps/20-paperless-ngx/data/export:/usr/src/paperless/export
      - /volume1/my_apps/20-paperless-ngx/data/consume:/usr/src/paperless/consume
    networks:
      - db-net 
      - proxy
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db

networks:
  db-net:
    external: true
  proxy:
    external: true

