services:
  restic-backup:
    image: restic/restic:latest
    container_name: restic-backup

    restart: "no"

    environment:
      RESTIC_REPOSITORY: /repo
      RESTIC_PASSWORD: ${RESTIC_PASSWORD}

    volumes:
      # repository location
      - /onsite-backups/snapshots:/repo

      # restore dir
      - /volume1/homes/Ninarissa/restored_backups:/restore

    command: "restore latest --target /restore"
