version: "3"

services:
    vaultwarden:
        image: vaultwarden/server:1.31.0
        container_name: vaultwarden
        restart: always
        expose:
          - 80
        environment:
            # - WEBSOCKET_ENABLED=true # Disable WebSocket if not needed or if causing issues
            # Admin token will be added here later
            # ADMIN_TOKEN: 'YOUR_SECURE_ADMIN_TOKEN_HASH'
            # Set timezone (Important for logs and Fail2Ban)
            TZ: "Europe/Berlin" # Adjust this to your time zone
        volumes:
            - ./vw-data:/data
            # Mounts for time zone (Important for correct log times -> Fail2Ban)
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
        user: '1000:10' 
        networks:
          - proxy

networks:
  proxy:
    external: true
