# More information at https://docs.kanboard.org/v1/admin/docker/
name: kanboard
services:
  app:
    image: docker.io/kanboard/kanboard:v1.2.52
    container_name: kanboard
    restart: always
    ports:
     - "8003:80"
     - "8343:443"
    volumes:
     - ./data:/var/www/app/data
     - ./plugins:/var/www/app/plugins
     - ./certs:/etc/nginx/ssl
    environment:
      DATABASE_URL: postgres://kanboard:kanboard-secret@db:5432/kanboard
    networks:
      - db-net

networks:
  db-net:
    external: true

