apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: postgres
  replicas: 1

  selector:
    matchLabels:
      app: postgres

  template:
    metadata:
      labels:
        app: postgres

    spec:
      containers:
        - name: postgres
          image: postgres:18
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 5432
              name: postgres

          envFrom:
            - secretRef:
                name: postgres-secret

          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql

      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data
