services:
  restic-backup:
    image: restic/restic:latest
    container_name: restic-backup

    restart: "no"

    environment:
      RESTIC_REPOSITORY: /repo
      RESTIC_PASSWORD: ${RESTIC_PASSWORD}

    volumes:
      # data to back up
      - /volume1/homes/Ninarissa/backups:/data:ro

      # repository location
      - /onsite-backups/snapshots:/repo

    command: "backup /data"
