---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Administration:
    - Kanboard:
        href: http://192.168.2.191:8003
        description: Issue Tracker
        icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/kanboard.svg
    - Paperless:
        href: http://192.168.2.191:8000/dashboard
        description: Central document management system
        icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/paperless-ngx.svg
        widget:
          type: paperlessngx
          url: http://192.168.2.191:8000
          username: paperless-admin
          password: "@D$TX8+L7R$Ed#S"

- Financial Services:
    - Larissa's Portfolio:
        href: https://app.parqet.com/p/overview
        description: Link to proprietary Parqet instance
    - Retirement Projection:
        href: https://parqet-companion.littlenerdy.net/retirement
        description: Link to Parqet integration
    - Hahabu:
        href: https://mein.hahabu.de/
        description: Link to proprietary Budgeting app

- Technical:
    - Speedport:
        href: http://192.168.2.1/html/login/index.html
        description: Our Speedport Smart 4 router
    - Homepage Documentation:
        href: https://gethomepage.dev/widgets/
        description: How to expand this homepage
