---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Administration:
    - Paperless:
        href: http://192.168.2.184:8000/dashboard
        description: Central document management system
        icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/paperless-ngx.svg
        widget:
          type: paperlessngx
          url: http://192.168.2.184:8000
          username: paperless-admin
          password: "@D$TX8+L7R$Ed#S"
    - Vaultwarden:
        href: https://192.168.2.184:8443/#/login
        description: Central password manager
        icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/vaultwarden-light.svg

- Financial Services:
    - Larissa's Portfolio:
        href: https://app.parqet.com/p/overview
        description: Link to proprietary Parqet instance

- Technical:
    - Ugreen GUI:
        href: http://192.168.2.184:9999/desktop/?os=ugospro#/login/account
        description: Graphical interface for NAS
    - Speedport:
        href: http://192.168.2.1/html/login/index.html
        description: Our Speedport Smart 4 router
    - Homepage Documentation:
        href: https://gethomepage.dev/widgets/
        description: How to expand this homepage
